name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy backend to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd linkedin_campaign
            git pull origin main
            cd backend
            npm install
            npm run build
            pm2 restart index
